apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: us-central1-docker.pkg.dev/se-gcp-401111/grade-demo/grade-submission-api
    newTag: 

resources:
  - ../../base
  - east1-service.yaml

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: store