apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: grade-backend-config
spec:
  healthCheck:
    type: HTTP
    requestPath: /grades
    port: 3000
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
