apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  labels:
    app: grade-submission
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grade-submission
  template:
    metadata:
      labels:
        app: grade-submission
    spec:
      containers:
      - name: grade-submission-api
        image: us-docker.pkg.dev/se-gcp-401111/grade-demo/grade-submission-api
        ports:
          - containerPort: 3000
